### ISSUE TITLE
[Feature Request] Enable Dependabot for live dependency updates

### ISSUE THREAD

**Issue by apoclyps** [ajurna/cbwebreader#6]
### Request

[Dependabot](https://dependabot.com/) automates dependency updates by creating pull requests to keep a project's dependencies secure and up-to-date. It is free to use for open source project's and avoids developers dedicating time to maintaining a project's dependencies.

### How dependabot works

1. Dependabot checks for updates: Dependabot pulls down your dependency files and looks for any outdated or insecure requirements.
2. Dependabot opens pull requests: If any of your dependencies are out-of-date, Dependabot opens individual pull requests to update each one.
3. You review and merge: You check that your tests pass, scan the included changelog and release notes, then hit merge with confidence.

### Proposal

A `.dependabot` hidden directory would be added to the project containing a `config.yml` file containing the following configuration for live updates:

```yml
version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    default_labels:
      - "Status: Review Needed"
      - "Scope: Backend"
      - "Type: Dependencies"
    allowed_updates:
      - match:
           update_type: "live"
```

Once configured, the project would then need to be grant access to the repository for dependabot via its website.

### Links to resources

* Validated using https://dependabot.com/docs/config-file/validator/
* Configured using https://dependabot.com/docs/config-file/
